In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

## Explorando os dados

In [2]:
df_train = pd.read_csv('train.csv')

In [3]:
df_test = pd.read_csv('test.csv')

In [4]:
df_test.head(2)

,NU_INSCRICAO,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q006,Q024,Q025,Q026,Q027,Q047
0,ba0cc30ba34e7a46764c09dfc38ed83d15828897,43,RS,19,F,1,1,1,3,1,...,NaN,NaN,E,E,H,B,B,C,D,A
1,177f281c68fa032aedbd842a745da68490926cd2,15,PA,24,M,3,2,1,4,1,...,NaN,NaN,B,C,B,A,A,C,D,A

In [5]:
df_train.head(2)

,Unnamed: 0,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,...,Q041,Q042,Q043,Q044,Q045,Q046,Q047,Q048,Q049,Q050
0,1,ed50e8aaa58e7a806c337585efee9ca41f1eb1ad,2016,4314902,Porto Alegre,43,RS,24,M,0.0,...,5.0,A,A,A,A,A,A,A,B,D
1,2,2c3acac4b33ec2b195d77e7c04a2d75727fad723,2016,2304707,Granja,23,CE,17,F,0.0,...,NaN,A,A,C,A,B,A,A,C,A

## Deixando so as colunas necessárias em df_train

In [6]:
colunas_teste = list(df_test.columns)

In [7]:
colunas_teste.append('IN_TREINEIRO')

In [8]:
df_train = df_train[colunas_teste]

In [9]:
df_train.head(2)

,NU_INSCRICAO,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,NU_NOTA_REDACAO,Q001,Q002,Q006,Q024,Q025,Q026,Q027,Q047,IN_TREINEIRO
0,ed50e8aaa58e7a806c337585efee9ca41f1eb1ad,43,RS,24,M,1,1,1,4,1,...,520.0,D,D,C,A,A,C,H,A,0
1,2c3acac4b33ec2b195d77e7c04a2d75727fad723,23,CE,17,F,3,1,2,0,2,...,580.0,A,A,B,A,A,A,NaN,A,0

In [10]:
df_train.describe()

,CO_UF_RESIDENCIA,NU_IDADE,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,TP_DEPENDENCIA_ADM_ESC,IN_BAIXA_VISAO,...,NU_NOTA_LC,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,IN_TREINEIRO
count,13730.000000,13730.000000,13730.000000,13730.000000,13730.000000,13730.000000,13730.000000,4282.000000,4282.000000,13730.000000,...,10133.000000,13730.000000,10133.000000,10133.000000,10133.000000,10133.000000,10133.000000,10133.000000,10133.000000,13730.000000
mean,30.736708,21.593809,2.185652,1.048871,1.782666,2.146176,1.353532,1.178888,2.259692,0.001238,...,516.472841,0.593664,1.101747,119.811704,111.915918,106.824238,113.123951,77.372446,529.048258,0.129862
std,9.862405,7.043654,1.007285,0.258895,0.880734,3.217328,0.558472,0.565490,0.698586,0.035167,...,68.688190,0.491167,0.700100,29.846017,33.737588,34.341349,33.480033,43.067140,154.294758,0.336163
min,11.000000,13.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,23.000000,17.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,2.000000,0.000000,...,468.100000,0.000000,1.000000,120.000000,100.000000,80.000000,100.000000,40.000000,440.000000,0.000000
50%,31.000000,19.000000,3.000000,1.000000,2.000000,0.000000,1.000000,1.000000,2.000000,0.000000,...,520.900000,1.000000,1.000000,120.000000,120.000000,120.000000,120.000000,80.000000,540.000000,0.000000
75%,35.000000,23.000000,3.000000,1.000000,2.000000,3.000000,2.000000,1.000000,2.000000,0.000000,...,564.900000,1.000000,1.000000,140.000000,120.000000,120.000000,120.000000,100.000000,600.000000,0.000000
max,53.000000,67.000000,5.000000,4.000000,4.000000,10.000000,4.000000,3.000000,4.000000,1.000000,...,763.600000,1.000000,9.000000,200.000000,200.000000,200.000000,200.000000,200.000000,1000.000000,1.000000

In [11]:
df_train_corr = df_train.corr()
df_train_corr

,CO_UF_RESIDENCIA,NU_IDADE,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,TP_DEPENDENCIA_ADM_ESC,IN_BAIXA_VISAO,...,NU_NOTA_LC,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,IN_TREINEIRO
CO_UF_RESIDENCIA,1.000000,-0.002017,-0.234786,0.009433,0.025822,-0.032538,0.041406,0.018145,0.079229,0.001360,...,0.128479,-0.096473,-0.016955,0.069195,0.047746,0.050400,0.061881,0.043565,0.060629,-0.034944
NU_IDADE,-0.002017,1.000000,0.009675,-0.017713,-0.253403,0.681435,-0.296328,0.516253,-0.082980,0.027907,...,-0.024979,0.082065,0.055675,-0.102243,-0.114181,-0.104293,-0.110452,-0.086709,-0.116125,-0.295091
TP_COR_RACA,-0.234786,0.009675,1.000000,0.015761,0.000738,0.003942,-0.041713,0.040504,-0.172229,-0.014715,...,-0.168624,0.116860,0.020586,-0.097606,-0.090291,-0.096344,-0.102936,-0.091136,-0.107840,0.009676
TP_NACIONALIDADE,0.009433,-0.017713,0.015761,1.000000,-0.000054,-0.026154,0.024070,0.020522,-0.012981,0.009354,...,-0.049631,0.015266,0.005211,-0.031126,-0.030800,-0.027184,-0.031422,-0.025561,-0.032759,-0.015179
TP_ST_CONCLUSAO,0.025822,-0.253403,0.000738,-0.000054,1.000000,-0.592834,0.156222,NaN,NaN,0.018096,...,-0.117616,-0.025174,0.037078,-0.105647,-0.110186,-0.114245,-0.117711,-0.089861,-0.120580,0.533983
TP_ANO_CONCLUIU,-0.032538,0.681435,0.003942,-0.026154,-0.592834,1.000000,-0.422308,NaN,NaN,-0.000956,...,0.077917,0.061881,0.005578,0.027881,0.006023,0.011259,0.022018,0.003954,0.015097,-0.257710
TP_ESCOLA,0.041406,-0.296328,-0.041713,0.024070,0.156222,-0.422308,1.000000,-0.047195,0.975328,-0.007455,...,0.037254,-0.070008,-0.026380,0.059108,0.084441,0.079996,0.068909,0.071172,0.082520,-0.244562
TP_ENSINO,0.018145,0.516253,0.040504,0.020522,NaN,NaN,-0.047195,1.000000,-0.037207,0.017366,...,-0.092792,0.018257,0.040453,-0.088155,-0.115773,-0.107252,-0.114830,-0.103573,-0.119816,NaN
TP_DEPENDENCIA_ADM_ESC,0.079229,-0.082980,-0.172229,-0.012981,NaN,NaN,0.975328,-0.037207,1.000000,-0.033257,...,0.299387,-0.165051,-0.049705,0.233368,0.282586,0.282997,0.264291,0.252388,0.297040,NaN
IN_BAIXA_VISAO,0.001360,0.027907,-0.014715,0.009354,0.018096,-0.000956,-0.007455,0.017366,-0.033257,1.000000,...,0.000096,0.003828,0.029456,-0.027909,-0.018751,-0.020515,-0.023665,-0.013298,-0.022911,-0.013602
IN_CEGUEIRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IN_SURDEZ,-0.010716,0.006520,0.007852,0.011142,0.013379,-0.011546,0.001588,0.050508,-0.023510,-0.000672,...,-0.029438,0.000246,0.032595,-0.029672,-0.016886,-0.032884,-0.033759,-0.021283,-0.030017,-0.007374
IN_DISLEXIA,0.003689,0.000492,-0.010046,-0.001611,-0.007585,0.004918,-0.005403,NaN,NaN,-0.000300,...,0.014425,-0.010316,-0.001444,0.001727,0.003853,0.005258,0.003524,0.016754,0.007788,-0.003297
IN_DISCALCULIA,0.001093,-0.004355,0.006900,-0.001611,0.002106,-0.005693,0.025162,0.022195,0.038079,-0.000300,...,-0.003901,-0.010316,-0.001444,0.000063,0.002381,-0.007760,0.002040,0.005220,0.000705,-0.003297
IN_SABATISTA,-0.029933,0.004965,0.017208,0.012926,-0.022877,0.011686,-0.008016,0.052293,0.002384,-0.003482,...,-0.007455,0.000065,0.015438,0.020032,0.019780,0.012722,0.025276,0.006091,0.018216,0.003824
IN_GESTANTE,-0.009503,0.006482,-0.010376,-0.005811,-0.008536,0.008906,-0.011008,0.031392,-0.008037,-0.001084,...,0.004152,0.015826,-0.002888,0.010113,0.004762,0.004731,-0.004822,0.003520,0.003987,-0.011893
IN_IDOSO,-0.014365,0.074384,0.009759,-0.002279,-0.010727,0.023838,-0.007641,NaN,NaN,-0.000425,...,-0.009528,0.009986,-0.001444,-0.013253,0.002381,-0.007760,0.002040,0.000606,-0.003158,-0.004663
TP_PRESENCA_CN,-0.035438,-0.245190,-0.024471,-0.020359,0.054831,-0.216379,0.173854,-0.182264,0.096449,-0.008757,...,0.007395,-0.041118,-0.002725,0.023033,0.022288,0.023703,0.028095,0.026419,0.028075,0.094692
TP_PRESENCA_CH,-0.035438,-0.245190,-0.024471,-0.020359,0.054831,-0.216379,0.173854,-0.182264,0.096449,-0.008757,...,0.007395,-0.041118,-0.002725,0.023033,0.022288,0.023703,0.028095,0.026419,0.028075,0.094692
TP_PRESENCA_LC,-0.034287,-0.241092,-0.021861,-0.024097,0.053252,-0.216059,0.177822,-0.194518,0.099585,-0.007335,...,NaN,-0.049031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.092454
TP_PRESENCA_MT,-0.034287,-0.241092,-0.021861,-0.024097,0.053252,-0.216059,0.177822,-0.194518,0.099585,-0.007335,...,NaN,-0.049031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.092454
NU_NOTA_CN,0.084534,-0.056171,-0.149429,-0.039746,-0.111134,0.040447,0.083383,-0.100504,0.393774,-0.007359,...,0.545667,-0.217892,-0.081150,0.357672,0.412894,0.429447,0.407747,0.416349,0.459938,-0.037874
NU_NOTA_CH,0.122825,-0.001611,-0.161831,-0.049801,-0.139415,0.088827,0.052710,-0.085401,0.338486,-0.005793,...,0.692988,-0.219352,-0.114706,0.443809,0.488050,0.510452,0.488797,0.494798,0.550582,-0.053460
NU_NOTA_LC,0.128479,-0.024979,-0.168624,-0.049631,-0.117616,0.077917,0.037254,-0.092792,0.299387,0.000096,...,1.000000,-0.236956,-0.117688,0.430603,0.453262,0.475390,0.467356,0.441696,0.512908,-0.028261
TP_LINGUA,-0.096473,0.082065,0.116860,0.015266,-0.025174,0.061881,-0.070008,0.018257,-0.165051,0.003828,...,-0.236956,1.000000,0.026255,-0.134679,-0.133054,-0.139382,-0.142948,-0.132294,-0.154111,-0.036395
TP_STATUS_REDACAO,-0.016955,0.055675,0.020586,0.005211,0.037078,0.005578,-0.026380,0.040453,-0.049705,0.029456,...,-0.117688,0.026255,1.000000,-0.583467,-0.482149,-0.452122,-0.491102,-0.261122,-0.498365,0.006688
NU_NOTA_COMP1,0.069195,-0.102243,-0.097606,-0.031126,-0.105647,0.027881,0.059108,-0.088155,0.233368,-0.027909,...,0.430603,-0.134679,-0.583467,1.000000,0.756664,0.759452,0.824538,0.558587,0.862744,-0.008709
NU_NOTA_COMP2,0.047746,-0.114181,-0.090291,-0.030800,-0.110186,0.006023,0.084441,-0.115773,0.282586,-0.018751,...,0.453262,-0.133054,-0.482149,0.756664,1.000000,0.875447,0.808006,0.655915,0.918278,-0.023308
NU_NOTA_COMP3,0.050400,-0.104293,-0.096344,-0.027184,-0.114245,0.011259,0.079996,-0.107252,0.282997,-0.020515,...,0.475390,-0.139382,-0.452122,0.759452,0.875447,1.000000,0.827151,0.664350,0.925813,-0.030147
NU_NOTA_COMP4,0.061881,-0.110452,-0.102936,-0.031422,-0.117711,0.022018,0.068909,-0.114830,0.264291,-0.023665,...,0.467356,-0.142948,-0.491102,0.824538,0.808006,0.827151,1.000000,0.635018,0.914505,-0.025958
NU_NOTA_COMP5,0.043565,-0.086709,-0.091136,-0.025561,-0.089861,0.003954,0.071172,-0.103573,0.252388,-0.013298,...,0.441696,-0.132294,-0.261122,0.558587,0.655915,0.664350,0.635018,1.000000,0.816248,-0.025811
NU_NOTA_REDACAO,0.060629,-0.116125,-0.107840,-0.032759,-0.120580,0.015097,0.082520,-0.119816,0.297040,-0.022911,...,0.512908,-0.154111,-0.498365,0.862744,0.918278,0.925813,0.914505,0.816248,1.000000,-0.026328
IN_TREINEIRO,-0.034944,-0.295091,0.009676,-0.015179,0.533983,-0.257710,-0.244562,NaN,NaN,-0.013602,...,-0.028261,-0.036395,0.006688,-0.008709,-0.023308,-0.030147,-0.025958,-0.025811,-0.026328,1.000000

In [12]:
corr_treino = df_train_corr.loc['IN_TREINEIRO']
corr_treino

CO_UF_RESIDENCIA         -0.034944
NU_IDADE                 -0.295091
TP_COR_RACA               0.009676
TP_NACIONALIDADE         -0.015179
TP_ST_CONCLUSAO           0.533983
TP_ANO_CONCLUIU          -0.257710
TP_ESCOLA                -0.244562
TP_ENSINO                      NaN
TP_DEPENDENCIA_ADM_ESC         NaN
IN_BAIXA_VISAO           -0.013602
IN_CEGUEIRA                    NaN
IN_SURDEZ                -0.007374
IN_DISLEXIA              -0.003297
IN_DISCALCULIA           -0.003297
IN_SABATISTA              0.003824
IN_GESTANTE              -0.011893
IN_IDOSO                 -0.004663
TP_PRESENCA_CN            0.094692
TP_PRESENCA_CH            0.094692
TP_PRESENCA_LC            0.092454
TP_PRESENCA_MT            0.092454
NU_NOTA_CN               -0.037874
NU_NOTA_CH               -0.053460
NU_NOTA_LC               -0.028261
TP_LINGUA                -0.036395
TP_STATUS_REDACAO         0.006688
NU_NOTA_COMP1            -0.008709
NU_NOTA_COMP2            -0.023308
NU_NOTA_COMP3            -0.030147
NU_NOTA_COMP4            -0.025958
NU_NOTA_COMP5            -0.025811
NU_NOTA_REDACAO          -0.026328
IN_TREINEIRO              1.000000
Name: IN_TREINEIRO, dtype: float64

In [13]:
variaveis = corr_treino[(corr_treino >= 0.25) | (corr_treino <= -0.25)]

In [14]:
variaveis = variaveis.index

In [15]:
variaveis

Index(['NU_IDADE', 'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'IN_TREINEIRO'], dtype='object')

## --- Criação do modelo ---

In [16]:
df_train = df_train[variaveis]

In [17]:
df_train.head(2)

   NU_IDADE  TP_ST_CONCLUSAO  TP_ANO_CONCLUIU  IN_TREINEIRO
0        24                1                4             0
1        17                2                0             0

In [18]:
y_train = df_train['IN_TREINEIRO']
X_train = df_train.drop(columns = 'IN_TREINEIRO')

In [19]:
X_test = df_test[X_train.columns]

In [20]:
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [21]:
classifier = RandomForestClassifier(n_estimators = 100, random_state = 42)

In [22]:
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [23]:
y_pred_test = classifier.predict(X_test)

In [24]:
df_answer = pd.DataFrame()
df_answer['NU_INSCRICAO'] = df_test['NU_INSCRICAO']
df_answer['IN_TREINEIRO'] = y_pred_test
df_answer

                                  NU_INSCRICAO  IN_TREINEIRO
0     ba0cc30ba34e7a46764c09dfc38ed83d15828897             0
1     177f281c68fa032aedbd842a745da68490926cd2             0
2     6cf0d8b97597d7625cdedc7bdb6c0f052286c334             1
3     5c356d810fa57671402502cd0933e5601a2ebf1e             0
4     df47c07bd881c2db3f38c6048bf77c132ad0ceb3             0
...                                        ...           ...
4565  361b7fcd8867119550fe2af5aa729ffad89a7cf5             0
4566  d8a0e4c9e29494cc9bba2422bd79333931475ee1             0
4567  3f1c3388244df8d6521e983a809292d9f3bca643             0
4568  1778e9c4cef591beb6b986d191d15ed05de816b0             0
4569  096809759695097e384e766d2d9e23a34fc81610             0

[4570 rows x 2 columns]

In [25]:
df_answer.to_csv('answer.csv', index=False, header=True)